library(devtools)
devtools::document()
devtools::create('pgr')
devtools::use_package('RPostgreSQL')
devtools::use_package('lazyeval')
devtools::use_package('readxl')
devtools::use_package('foreign')
devtools::use_package('dplyr')
